export const CART_ADD_ITEM_START = 'CART_ADD_ITEM_START';
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_ADD_ITEM_FAILURE = 'CART_ADD_ITEM_FAILURE';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
