export const USER_LOGIN_REQUEST_START = 'USER_LOGIN_REQUEST_START';
export const USER_LOGIN_REQUEST_SUCCESS = 'USER_LOGIN_REQUEST_SUCCESS';
export const USER_LOGIN_REQUEST_FAILURE = 'USER_LOGIN_REQUEST_FAILURE';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';

export const USER_REGISTER_REQUEST_START = 'USER_REGISTER_REQUEST_START';
export const USER_REGISTER_REQUEST_SUCCESS = 'USER_REGISTER_REQUEST_SUCCESS';
export const USER_REGISTER_REQUEST_FAILURE = 'USER_REGISTER_REQUEST_FAILURE';

export const USER_PROFILE_REQUEST_START = 'USER_PROFILE_REQUEST_START';
